version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/angular-app

permissions:
  - object: /var/www/html/angular-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/build_angular_app.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_angular_app.sh
      timeout: 300
      runas: root
